import EditProfileContent from '../../../app/containers/Profile/EditProfile/EditProfile'
import Head from 'next/head'
import Layout from '../../../app/components/LayOut/Layout'
import { Box } from '@chakra-ui/layout'
import MobileEditProfile from '../../../app/containers/Profile/EditProfile/MobileEditeProfil/MobileEditProfile'

export default function EditProfile() {
  return (
    <div>
      <Head>
        <title>EditProfile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout 
        link='/me/profile/profile'
        linkName='Profile'
        currentPage='Edit Profile and Preferences'
        slash='/'
      >

        <Box display="flex" justifyContent="space-between">
          <EditProfileContent/>
          <MobileEditProfile/>
        </Box>

      </Layout>
    </div>
  )
}