import { Button } from '@chakra-ui/button'
import { Box } from '@chakra-ui/layout'
import Head from 'next/head'
import Layout from '../../../app/components/LayOut/Layout'
import InfoProfile from '../../../app/containers/Profile/InfoProfile'
import CenterProfile from '../../../app/containers/Profile/CenterProfile'
import ProfileMobile from '../../../app/containers/Profile/MobileBlog/ProfileMobile'
import UpcomingGigsCard from '../../../app/components/UpcomingGigsCard/UpcomingGigsCard'
import JobItem from '../../../app/components/JobItem/JobItem'
import NextLink from 'next/link'

export const getStaticProps = async () => {

  const res = await fetch('https://jsonplaceholder.typicode.com/users?_limit=3')
  const data = await res.json()
  
  return {props: {Amulo: data}}

}

export default function Profile({Amulo}) {
  
  return (
    <div>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout 
        currentPage='Profile'
        linkButton={<NextLink href='/me/profile/editProfile'><Button colorScheme="purple" w="120px" fontWeight="normal" marginLeft="25px">EDIT PROFILE</Button></NextLink>}
        editProfil={'editProfil'}
      >
        <Box display="flex"  justifyContent="space-between">
          <ProfileMobile
            upcomingGigsCard={
              Amulo.map(item =>  
              <NextLink href={'/me/job/' + item.id + '/info'} key={item.id} >
                  <Box w='100%' >
                    <UpcomingGigsCard
                      job={item.name}
                    />        
                  </Box>
              </NextLink>,
            )}
            jobItem={  
              Amulo.map(item =>  
                <NextLink href={'/me/job/' + item.id + '/info'} key={item.id} >
                  <Box cursor='pointer' width={{md:"48.5%",sm:"96vw",base:"96vw"}} padding="2vw" borderRadius="4px" border="0.7px solid #DDE2E5" >
                    <JobItem
                      image="https://allears.net/wp-content/uploads/2020/06/Uber-logo.jpg"
                      companyName={item.name}  
                    /> 
                  </Box>   
                </NextLink>
              )}
            />



          <Box d={{base:'none' , sm:"none" , md:'none' , lg:'block', xl:'block' }} w='100%' >
            <CenterProfile
              jobItem={  
                Amulo.map(item =>  
                  <NextLink href={'/me/job/' + item.id + '/info'} key={item.id} >
                    <Box  cursor='pointer' width={{md:"48.5%",sm:"96vw",base:"96vw"}} padding="2vw" borderRadius="4px" border="0.7px solid #DDE2E5" >
                      <JobItem
                        image="https://allears.net/wp-content/uploads/2020/06/Uber-logo.jpg"
                        companyName={item.name}  
                      /> 
                    </Box>   
                  </NextLink>
                )}
              />
          </Box>
          <Box d={{base:'none' , sm:"none" , md:'none' , lg:'block', xl:'block' }} >
            
            <InfoProfile
              upcomingGigsCard={
                Amulo.map(item =>  
                <NextLink href={'/me/job/' + item.id + '/info'} key={item.id} >
                  <Box w='100%' >
                    <UpcomingGigsCard
                      job={item.name}
                    />        
                  </Box>
                </NextLink>
              )}
            />
          </Box>
        </Box>

      </Layout>
    </div>
  )
}