import React from "react";
import Head from "next/head";
import RoutedApplyPage from "../../../../app/containers/ApplyPage/RoutedApplyPage";

export const getStaticPaths = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/users');
  const data = await res.json();

  const paths = data.map(item => {
    return {
      params: { id: item.id.toString() }
    }
  })

  return {
    paths,
    fallback: false
  }
}

export const getStaticProps = async (context) => {
  const res1 = await fetch('https://jsonplaceholder.typicode.com/users?_limit=4')
  const data1 = await res1.json()


  const id = context.params.id;
  const res = await fetch('https://jsonplaceholder.typicode.com/users/' + id);
  const data = await res.json();

  return {

    props: { item: data, ninja: data1 }

  }
}

export default function Home({item, ninja}) {
  return (
    <div>
      <Head>
        <title>Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RoutedApplyPage ninja={ninja} item={item} />
    </div>
  )
}