import Head from 'next/head'
import Layout from '../../../../app/components/LayOut/Layout'
import { Box } from '@chakra-ui/layout'
import { Input } from '@chakra-ui/react'
import { Search2Icon } from '@chakra-ui/icons';
import BlogReadme from '../../../../app/containers/BlogPage/content/BlogInfo/BlogReadme';
import BlogBigPost from '../../../../app/components/BlogPosts/BlogBigPost';
import BlogPosts from '../../../../app/components/BlogPosts/Post';
import Link from 'next/link';

export const getStaticPaths = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/users');
  const data = await res.json();

  const paths = data.map(item => {
    return {
      params: { id: item.id.toString() }
    }
  })

  return {
    paths,
    fallback: false
  }
}

export const getStaticProps = async (context) => {
  const res1 = await fetch('https://jsonplaceholder.typicode.com/users?_limit=4')
  const data1 = await res1.json()

  const id = context.params.id;
  const res = await fetch('https://jsonplaceholder.typicode.com/users/' + id);
  const data = await res.json();

  return {

    props: { item: data, ninja: data1 }

  }
}

export default function BlogRead({item, ninja}) {
  return (
    <div>
      <Head>
        <title>Blog Info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout 
        link='/blog/blog'
        linkName='News and Blog'
        currentPage='Built to Last: A collection of Inspiring Stories from Foremost Entrepreneurs'
        slash='>'

        searchInput={
          <Box margin="30px 0" width="389px" height="40px" padding="7px 20px" borderRadius="4px" display="flex" alignItems="center" background="#F5F4F6" >
            <Search2Icon color="#603E94" />
            <Input paddingLeft="15px" variant="unstyled" placeholder="Search Academy courses and classes..." />
          </Box>
        }>

        <Box  w="100%" display="flex" justifyContent="space-between">
            <BlogReadme 
              blogBigPost={
                <BlogBigPost
                  postTitle={item.name}
                />
              }

              post={
                ninja.map(items => 
                  <Link href={'/blog/' + items.id + '/blogRead'} key={items.id}>
                    <a href="">
                      <BlogPosts
                        course={items.name}
                        />
                    </a>
                  </Link>
                )
               }
            />
        </Box>

      </Layout>
    </div>
  )
}