import { Input } from '@chakra-ui/react'
import Head from 'next/head'
import Layout from '../../app/components/LayOut/Layout.jsx'
import Academy from '../../app/containers/Academy/Academy'
import { Text } from '@chakra-ui/layout';
import EmptyAcademyPage from '../../app/containers/Academy/empty/EmptyAcademyPage.jsx';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Academy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout 
        currentPage={<Text margin="30px -25px 30px 0 " fontWeight="600" fontSize="16px" lineHeight="19,2">Academy</Text>}
        searchInput={<Input  w={{lg:"18vw" , base:"75vw"}}  placeholder="Search "/>} 
        searchIcon={"searchIcon"}
        filter={"filter"}
        > 
        { false ?( <EmptyAcademyPage/>)
        : (<Academy />)}
        
      </Layout>
    </div>
  )
}
