import Head from 'next/head'
import RoutedJobs from '../../../app/containers/jobs/RoutedJobs'


export const getStaticProps = async () => {

  const res = await fetch('https://jsonplaceholder.typicode.com/users?_limit=9')
  const data = await res.json()
  
  return {
    props: {ninja: data}
  }

}


export default function Home({ninja}) {
  return (
    <div>
      <Head>
        <title>Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RoutedJobs ninja={ninja} />
    </div>
  )
}
