import Head from 'next/head'
import AboutPage from '../app/containers/WebSite/AboutPage/AboutPage'
import LayoutWebsite from '../app/components/Website/Layout/LayoutWebsite'


export default function Home() {
  return (
    <div>
      <Head>
        <title>About-Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutWebsite>
        <AboutPage/>
      </LayoutWebsite>
    </div>
  )
}