import Head from 'next/head'
import BlogPage from '../app/containers/WebSite/BlogPage/BlogPage'
import LayoutWebsite from '../app/components/Website/Layout/LayoutWebsite'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blog-page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutWebsite>
        <BlogPage/>
      </LayoutWebsite>
    </div>
  )
}