import Head from 'next/head'
import LayoutWebsite from '../app/components/Website/Layout/LayoutWebsite'
import Gigamarket from '../app/containers/WebSite/GigaMarket/Gigamarket'

export default function Home() {
  return (
    <>
      <Head>
        <title>Giga - Market</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutWebsite>
          <Gigamarket />
      </LayoutWebsite>
    </>
  )
}