import Head from 'next/head'
import LogInPage from '../app/containers/LogIn-SignUp/LogIn'
import Header from '../app/components/Website/Layout/Head'
import { Box } from '@chakra-ui/layout'

export default function Home() {
  return (
    <div>
        <Head>
          <title>Log-In</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head> 
        <Header singUp={true}>
          <Box mt={{base:'80px',sm:'95px',md:'110px',md:'120px', xl:'120px'}}>
            <LogInPage/>
          </Box> 
        </Header>  
    </div>
  )
}