import Head from 'next/head'
import SignUpPage from '../app/containers/LogIn-SignUp/SignUp'
import Header from '../app/components/Website/Layout/Head'
import { Box } from '@chakra-ui/layout'

export default function Home() {
  return (
    <div>
        <Head>
          <title>Sign-Up</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header logIn={true}>
          <Box mt={{base:'80px',sm:'95px',md:'110px',md:'120px', xl:'120px'}}>
            <SignUpPage/>
          </Box> 
        </Header>  
    </div>
  )
}